### ISSUE TITLE
Absolute paths not supported

### ISSUE THREAD

**Issue by dferber90** [seek-oss/html-sketchapp-cli#20]
First of all, thanks for pushing design systems and the ease of integration and syncing forward. We're working on a design system right now and the Seek Style Guide is a good inspiration. I saw you speak about css-modules at Reactive Conf Bratislava and I've been following your stuff for a long time :)

---

I tried out `html-sketchapp-cli` and at first thought it was not working correctly.
Turns out this is because `html-sketchapp-cli` does not support importing styles from absolute paths.

I had to use a relative path on the exports file to get the styles to work in Sketch:

```diff
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sketch Styleguide Import Page</title>
-    <link rel="stylesheet" href="/styles.css" />
+    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <div data-sketch-symbol="Button/Primary">
      <button class="red">Primary Button</button>
    </div>
  </body>
</html>
```

I resolved the problem by simply using a relative path, so I don't need a fix. However I wanted to make you aware of this.

**Comment by dferber90** [comment]
I just realised now that this is probably an issue of [brainly/html-sketchapp](https://github.com/brainly/html-sketchapp), not of this tool.

**Comment by markdalgleish** [comment]
Thanks for the nice comments! 😄 

What options did you provide to html-sketchapp-cli? If you're trying to open this as a file, absolute paths won't work—you'll need to use the `serve` option.

**Comment by dferber90** [comment]
Ah, makes total sense. I was using the `--file` option. Should have read the docs properly instead of just skimming them.

Sorry for the noise :)
