### ISSUE TITLE
Do nested symbols work?

### ISSUE THREAD

**Issue by shripadk** [seek-oss/html-sketchapp-cli#22]
I am trying to create nested symbols but html-sketchapp-cli is instead creating a separate symbol for the containing element. For example, assume this is the generated output:

```html
<div data-sketch-symbol="Container">
    <div data-sketch-symbol="Item/Red">A</div>
    <div data-sketch-symbol="Item/blue">B</div>
    <div data-sketch-symbol="Item/Green">C</div>
    <div data-sketch-symbol="Item/Brown">D</div>
    <div data-sketch-symbol="item/Cornflowerblue">E</div>
</div>
```

The current behaviour creates a separate `Container` symbol without the `Item` symbols nested within it. Is there a separate prop for the same that is undocumented?

**Comment by markdalgleish** [comment]
Sorry, I'm not entirely sure I follow. Could you go into a bit more detail about what you're expecting to happen in Sketch?

**Comment by mxmul** [comment]
This is a limitation that I've run up against as well. We have items in our styleguide that are composed of other styleguide components, and would like the generated Sketch symbols to retain that nested relationship.

The page that we run html-sketchapp-cli on looks something like this:

```html
<div data-sketch-symbol="Item/1">...</div>
<div data-sketch-symbol="Item/2">...</div>
<div data-sketch-symbol="Container">...</div>
```

where the "Container" symbol in Sketch contains a copy of the markup of `Item/1`, and there is no reference to the shared component/symbol. Somehow, I'd like to be able to tell html-sketchapp that this is actually an instance of the `Item` symbol declared above, so it can be easily swapped out for a different variant (e.g. `Item/2`) in Sketch.

**Comment by markdalgleish** [comment]
Honest question—why is important to maintain this relationship between symbols inside Sketch? Personally, I think of Sketch files as compiled output, and duplication of the internals of symbols doesn't bother me, but I feel like I might be missing something.

**Comment by shripadk** [comment]
@markdalgleish It's important because we are using React to compose components and would be great if we could compose the corresponding symbols as well. Imagine a simple scenario of a Button component and it's corresponding Button symbol. So far so good. But once we have a Button Toolbar component which has a corresponding Button Toolbar symbol, the Buttons within the Button Toolbar component are just renderings of the Button component and not a symbol that can be changed.

For example, react-sketchapp provides a way to create Nested Symbols which is demonstrated here: http://airbnb.io/react-sketchapp/docs/API.html#nested-symbol--override-example

**Comment by shripadk** [comment]
@markdalgleish I guess this video explains Nested symbols best: https://www.youtube.com/watch?v=7HaeAy31-_Q

**Comment by markdalgleish** [comment]
Thanks for that video! It really helped clear up my understanding here. I didn't realise you could swap out nested symbols like that.

@shripadk @mxmul Is this something that either of you would be interested in implementing? I could build it too, but it might take me some time to get around to it.

**Comment by mxmul** [comment]
I could definitely look into implementing it.
