### ISSUE TITLE
Sketch does show any elements when I upload the document.asketch.json and page.asketch.json

### ISSUE THREAD

**Issue by fareezahmed** [seek-oss/html-sketchapp-cli#49]
Hi Guys,

I followed the Install step and also installed "Almost Sketch" plugin but when I upload the .json file.
I see a blank sketch page no elements have been uploaded no change could be observed.

Thanks
Fareez

**Comment by kdzwinel** [comment]
This is probably more of a html-sketchapp issue than html-sketchapp-cli, so if you are still seeing the problem, please open issue at https://github.com/brainly/html-sketchapp/ and include said .asketch.json file so we can investigate.
