### ISSUE TITLE
Feature: generate sketch library file without using MacOS

### ISSUE THREAD

**Issue by phun-ky** [seek-oss/html-sketchapp-cli#59]
I don't think it is possible now, but if this is fixed: https://github.com/brainly/html-sketchapp/issues/99#issuecomment-406516489 is it possible to generate a sketch library file in the cli? It would make distribution of our styleguide much easier!

**Comment by markdalgleish** [comment]
Yes, it would be possible in that case. Closing this for now since it's a duplicate of the outstanding html-sketchapp issue.
