### ISSUE TITLE
Timeout when generating from a Storybook story

### ISSUE THREAD

**Issue by toolmantim** [seek-oss/html-sketchapp-cli#62]
When generating from a local Storybook server, you receive a request timeout error:

```
$ html-sketchapp --url 'http://localhost:6006/iframe.html?selectedKind=Sketch&selectedStory=Export' --out-dir dist
{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (buildkite/frontend/node_modules/puppeteer/lib/NavigatorWatcher.js:94:21) name: 'TimeoutError' }
```

Storybook keeps a webpack HMR event-stream socket open. Switching from `networkidle0` to `networkidle2` fixes it.

Given `networkidle2` is the recommended default event to use these days anyhow, perhaps you'd be open to a PR that replaces `networkidle0` with `networkidle2`?

Aside from this one glitch, this works perfectly w/ Storybook — you just create a story with a big Sketch export sheet, and point the CLI directly at it 👌🏼

**Comment by toolmantim** [comment]
> Since this is so common in dev environments, I'm definitely open to changing it.

🙏🏼

> It seems to me that networkidle2 could cause issues for pages that only have an external JS and CSS file, since it could consider the page loaded even while still downloading the assets—am I understanding this correctly? Maybe this needs to be configurable?

Yeah, I'm not sure. Perhaps "when page has no more then 2 network requests for half a second" would cause problems for things like you said. I'm guessing it might? So perhaps we need it to be configurable?

If it is configurable, I wonder what should be the default? If the default is `networkidle0`, for people that need `networkidle2` the experience will be hitting the 30s timeout and wondering why it's not working. If the default is `networkidle2`, for people that need `networkidle0` the experience (though I'm not 100% sure) would be they end up with missing assets/rendering errors in the export and wonder why that is.

Perhaps it's best to keep the default as `networkidle0` and perhaps add a nice message? I only knew where to go digging for because I've used `puppeteer` a bit.

🤔

> Do you have a source for this? I can't seem to find any advice on this.

Ah, mostly https://github.com/GoogleChrome/puppeteer/issues/1552#issuecomment-350954419 and the fact it's the default example of the Puppeteer readme these days.

**Comment by markdalgleish** [comment]
I feel like we could change the default to `networkidle2`, and add a `waitUntil` option to html-sketchapp-cli's config that passes the value through to Puppeteer. The readme could point you through to the Puppeteer API docs: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options

**Comment by toolmantim** [comment]
Sounds good. Happy to send through a PR for that now…
