### ISSUE TITLE
get-installed-path is failing to find html-sketchapp

### ISSUE THREAD

**Issue by jayfallon** [seek-oss/html-sketchapp-cli#8]
Error message I get upon `html-sketchapp install`

```
(node:6987) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: get-installed-path: module not found "html-sketchapp" in path /Users/jayfallon/.nvm/versions/node/v8.1.4/lib/node_modules/html-sketchapp
(node:6987) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by anilkk** [comment]
@markdalgleish PR https://github.com/seek-oss/html-sketchapp-cli/pull/9 should fix the UnhandledPromiseRejectionWarning.

**Comment by markdalgleish** [comment]
The unhandled rejection is a bit of a red herring (this project needs better error handling). This seems to be an issue with [get-install-path](https://www.npmjs.com/package/get-installed-path) being unable to find html-sketchapp, so I've renamed the issue.

**Comment by markdalgleish** [comment]
Unfortunately, I can't reproduce this issue, but I have a feeling this will fix it.

@jayfallon @bradbarrow Could one of you try making the following change to [these lines in cli.js](https://github.com/seek-oss/html-sketchapp-cli/blob/01a50a11a6ec6e1bf9810e92bf0c79139a9a1b5c/bin/cli.js#L112-L113) on your local machine and see if the problem persists?

```diff
-const { getInstalledPath } = require('get-installed-path');
-const htmlSketchappPath = await getInstalledPath('html-sketchapp');
+const htmlSketchappPath = path.dirname(require.resolve('html-sketchapp/package.json'));
```

**Comment by anilkk** [comment]
@markdalgleish I can confirm your above solution works fine.
I fixed this issue with hacky solution using getInstalledPath.
` let htmlSketchappPath = await getInstalledPath('html-sketchapp-cli');
    htmlSketchappPath = htmlSketchappPath  + 'node_modules/html-sketchapp';`

**Comment by jayfallon** [comment]
That worked for me, Mark. Thank you very much.

**Comment by markdalgleish** [comment]
I'll get a proper fix in soon, just reopening until then.
